Added MovieView
Coercivity/RollGO pull request #31
Opened 2023-12-12 13:08 UTC by serpens7

2023-12-12 16:11 UTC, slavoyar commented on src/WebApp/src/views/MoviePage.tsx
> +const MoviePage = () => {
Лучше сразу добавить на LobbyPage

2023-12-12 16:13 UTC, slavoyar commented on src/WebApp/src/components/Navbar.tsx
> +          </Link>
Здесь тоже Link Внутри Typography. В Typography надо только текст писать.

2023-12-12 16:14 UTC, slavoyar commented on src/WebApp/src/components/Navbar.tsx
> +          <Link href={Route.MOVIE} sx={{ color: 'white', fontWeight: 700, textDecoration: 'none' }}>
По поводу color там как-то можно использовать цвета из темы error success и так далее. Надо на них переделать. 

По поводу fontWeight и textDecoration. Можно в файле theme прописать это.

2023-12-12 16:19 UTC, slavoyar commented on src/WebApp/src/components/MovieView.tsx
> +  const [data, setData] = useState<Movie>();
Думаю лучше фильм через пропсы передавать.

2023-12-12 16:19 UTC, slavoyar commented on src/WebApp/package.json
> +    "webpack": "^5.89.0",
зачем webpack?

2023-12-15 17:10 UTC, slavoyar requested changes

2023-12-15 17:10 UTC, slavoyar commented on src/WebApp/src/views/LobbyPage.tsx
> +        <Typography variant="h3">Комната {lobbyId}.</Typography>
Локализация

2023-12-15 17:10 UTC, slavoyar commented on src/WebApp/src/models/Movie.ts
> +}
тут как-то многовато полей у Movie. Можно было добавить которые ты используешь пока что. А потом будем ориентироваться на наш бэк.

Можно не менять.

2023-12-15 17:10 UTC, slavoyar commented on src/WebApp/src/views/LobbyPage.tsx
> +import { Movie } from '../models/Movie';
Можешь использовать импорты с использованием @.
Если файлы лежат в текущей директории или в дочерней, то надо использовать относительный импорт `./subfolder/file`.
Иначе `@components/Component.tsx`

2023-12-15 17:10 UTC, slavoyar commented on src/WebApp/src/components/MovieSearch.tsx
> +}));
Такая стилизация как-то неправильно выглядит для меня. Это так в документации в Material UI?

2023-12-15 17:10 UTC, slavoyar commented on src/WebApp/src/components/MovieSearch.tsx
> +      <Search
Кажется что можно использовать компонент Box

2023-12-16 06:00 UTC, serpens7 commented on src/WebApp/src/models/Movie.ts
> +}
это пока для моковых данных. решил интерфейс прописать, так как пока неизвестно что из этого останется

2023-12-16 06:01 UTC, serpens7 commented on src/WebApp/src/views/LobbyPage.tsx
> +import { Movie } from '../models/Movie';
это скопированно из search компонента в примере mui

2023-12-16 06:02 UTC, serpens7 commented on src/WebApp/src/components/MovieSearch.tsx
> +}));
да, я тут почти ничего не менял

2023-12-16 16:53 UTC, slavoyar approved these changes

2023-12-16 16:53 UTC, merged

2023-12-16 16:53 UTC, serpens7 commented
украли коммит :(