UserView
Coercivity/RollGO pull request #4
Opened 2023-11-29 16:49 UTC by serpens7

2023-11-29 16:58 UTC, slavoyar requested changes

2023-11-29 16:58 UTC, slavoyar commented on src/WebApp/src/components/Navbar.tsx
> +interface NavbarProps {
Это убрать. User будет доставаться из стора.

2023-11-29 16:58 UTC, slavoyar commented on .devcontainer/devcontainer.json
> +// For format details, see https://aka.ms/devcontainer.json. For config options, see the
Этого файла вообще быть не должно. Надо добавить его в .gitignore.

2023-11-29 16:58 UTC, slavoyar commented on src/WebApp/src/components/UserView/UserView.tsx
> +  temp(): void;
Во-первых, переименовать temp (я так написал, потому что мне было лень придумывать).
Во-вторых, можно сделать следующее
```
interface UserViewProps extends ButtonBase {
  username: string;
}
...
...
<IconButton ...props className="navbar-btn" sx={{ p: 1 }} >
```

2023-11-29 22:25 UTC, kaayran commented
интересные вещи тут у вас происходят

2023-11-30 08:34 UTC, slavoyar approved these changes

2023-11-30 08:34 UTC, merged