lots of small fixes + mainPage changes
Coercivity/RollGO pull request #85
Opened 2024-01-21 13:54 UTC by serpens7

Closes #81 #82 #83

2024-01-21 17:08 UTC, slavoyar requested changes

2024-01-21 17:08 UTC, slavoyar commented on src/WebApp/src/components/common/LobbySettings.tsx
> +              inputProps={{ maxLength: '20' }}
А почему string, a не number?

2024-01-21 17:08 UTC, slavoyar commented on src/WebApp/vite.config.ts
> +        target: 'https://194.87.101.114:5228',
Осуждаем

2024-01-21 17:08 UTC, slavoyar commented on src/WebApp/src/store/userStore.ts
> +          isAnonymous: user.isAnonymous,
Лучше здесь просто false, а там где setUser вернуть как было data.user

2024-01-21 17:08 UTC, slavoyar commented on src/WebApp/src/components/common/LobbySettings.tsx
>    };
Почему это называется spinCount?

2024-01-26 18:29 UTC, SirichenkoNA commented
![изображение](https://github.com/Coercivity/RollGO/assets/79010101/d19988b1-f35f-48c0-93fe-c5ed40ac8610)

Если нужна заглавная буква, то это должно быть отражено в надписи!

2024-01-26 18:36 UTC, SirichenkoNA approved these changes

2024-01-26 18:36 UTC, slavoyar approved these changes

2024-01-26 18:36 UTC, merged